### ISSUE TITLE
Correcciones y consejos

### ISSUE THREAD

**Issue by Liluminalia** [LeanLu/202301-W2CH3-leandro-cova#7]
Buenas Leandro y Cova! esta genial en general, se nota que nos habéis escuchado un montón, hasta los nombres de los Commit están correctos, los describe tienen el nombre de la función, cosa que os va a servir un montón para detectar errores y el given when then perfecto, en general todo muy bien, lo único que os diría a modo de consejo es algo que veréis mas adelante:
- intentar no cargar un solo archivo con muchas funciones, por single responsability, hubiera estado perfect poniendo un archivo por cada función, pero vamos es un detalle, y es algo que vais a hacer durante todo el bootcamp, asi que no os preocupéis.

seguid asi!!! saludoss!

**Comment by LeanLu** [comment]
Gracias Sara! 😁😊🐱‍👓
